Robots new app config input types
enonic/app-robots-txt pull request #31
Opened 2023-08-09 15:48 UTC by poi33

2023-08-09 18:42 UTC, reisfmb commented on src/main/resources/services/robotstxt/robotstxt.js
> +    if (Array.isArray(group.disallow)) {
Suggestion... create a function:

```javascript
function composeBody(arr) {
    const forceArray = (el) => Array.isArray(el) ? el : [el];
    const keyValuesToString = (obj) => forceArray(obj.values).map(value => `${obj.key}: ${value}\n`).join('');
    
    return arr.reduce((acc, curr) => acc + keyValuesToString(curr), '');
}
```

and use it like:

```javascript
const body = composeBody([
    { key: "User-agent", values: group.userAgent },
    { key: "Allow", values: group.allow },
    { key: "Disallow", values: group.disallow }
]);
```

2023-08-09 18:45 UTC, reisfmb approved these changes

2023-08-10 08:41 UTC, alansemenov commented on src/main/resources/services/robotstxt/robotstxt.js
> +    const accept = req.headers.accept || req.headers.Accept;
`Request` object has `getHeader` method which can be used to get the Accept header. Header name parameter is case-insensitive (can be `req.getHeader('accept')` or `req.getHeader('Accept')`).

https://github.com/enonic/site-developer/blob/master/src/main/resources/site/parts/market-latest/market-latest.es#L89

2023-08-10 08:42 UTC, alansemenov commented on src/main/resources/services/robotstxt/robotstxt.js
> +    const accept = req.headers.accept || req.headers.Accept;
Documented [here](https://developer.enonic.com/docs/xp/stable/framework/http#http-request) (towards the bottom)

2023-08-10 08:44 UTC, alansemenov commented on src/main/resources/services/robotstxt/robotstxt.js
> +        return data;
Enough with one `return data;` after the `if...` block.

2023-08-10 08:47 UTC, alansemenov requested changes
A couple of cosmetic things to fix

2023-08-10 15:04 UTC, poi33 commented on src/main/resources/services/robotstxt/robotstxt.js
> +    if (Array.isArray(group.disallow)) {
Let me see if I can adopt this with a some modification

2023-08-14 06:57 UTC, alansemenov approved these changes

2023-08-16 13:23 UTC, merged